AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  air quality

  Sample SAM Template for air quality

Globals:
  Function:
    Timeout: 60

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world/
      Handler: app.sunrise_api_collector
      Runtime: python3.8
      Events:
        sunrise:
            Type: Schedule
            Properties: 
              Schedule: 'rate(4 minutes)'

  SunriseAPI:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: air-quality-cs3505-bucket